### ISSUE TITLE
parseJSON means

### ISSUE THREAD

**Issue by mayangulfiee** [9r3i/parser#1]
I think parseJSON is parse JSON string to object, this parser.parseJSON behavior is otherwise, like JSON.stringify but much prettier.

I don't know if anyone else has the same thought as mine.

But I suggest to rename the method to some thing else before it's getting famous. I hope so. :)

**Comment by 9r3i** [comment]
hahaha 😅
I think you're right, I'll rename it later.
what do you suggest then?
